// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://madymngifviixpttjpvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZHltbmdpZnZpaXhwdHRqcHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNjA2OTIsImV4cCI6MjA4MDkzNjY5Mn0.v9CF7B4oDk0zITMrLjwyXg8RfCLd5MNkL70WPlN0DcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);